Version 2

diff --git a/bin/fastcheck b/bin/fastcheck
--- a/bin/fastcheck
+++ b/bin/fastcheck
@@ -2,17 +2,8 @@
 
 set -e
 
-echo "Executing tslint"
-npm run lint
-if [ ! $? -eq 0 ]; then
-  echo '\033[31mYou have linting errors, attempting to fix them.\033[0m'
-  npm run fix
-  exit 1
-fi
-
-echo "Executing sass-lint"
-npm run sass-lint src/**/*.scss -v --max-warnings=0
-if [ ! $? -eq 0 ]; then
-  echo '\033[31mYou have linting errors.\033[0m'
+echo "Executing stylelint"
+if ! npm run css-lint; then
+  echo '\033[31mYou have CSS linting errors.\033[0m'
   exit 1
 fi
