Add scss linters

diff --git a/bin/fastcheck b/bin/fastcheck
--- a/bin/fastcheck
+++ b/bin/fastcheck
@@ -1,8 +1,16 @@
 #!/bin/sh
 
+echo "Executing tslint"
 yarn lint
 if [ ! $? -eq 0 ]; then
   echo -e '\033[31mYou have linting errors, attempting to fix them.\033[0m'
   yarn fix
+  exit 1
+fi
+
+echo "Executing sass-lint"
+yarn sass-lint src/**/*.scss -v --max-warnings=0
+if [ ! $? -eq 0 ]; then
+  echo -e '\033[31mYou have linting errors.\033[0m'
   exit 1
 fi
